version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: skypredict-api
    build: .
    container_name: skypredict
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI${MONGO_URI}${MONGOD_DATASET}
    depends_on:
      - mongo

volumes:
  mongo-data: