services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: skypredict
    ports:
      - "5000:5000"
    environment:
      - METEOSTAT_API_KEY=${METEOSTAT_API_KEY}
      - METEOSTAT_API_HOST=${METEOSTAT_API_HOST}
      - AEROAPI_KEY=${AEROAPI_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGOD_DB=${MONGOD_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    depends_on:
      - mongo

volumes:
  mongo-data:
